molanal: molanal.new.c
	gcc -O3 molanal.new.c -lm -o molanal

debug: molanal.new.c
	gcc -g -O3 molanal.new.c -lm -o molanal

old: molanal.old.c
	gcc -O3 molanal.old.c -lm -o molanal_old

clean:
	rm -f molanal molanal_old
